/*******************************************************************************
  LCD Module Source File

  File Name:
    lcd.c

  Summary:
    Non-blocking HD44780 1602IIC LCD driver over I2C1 for PIC32MX274F256B.

  Description:
    Drives a 16x2 HD44780-compatible LCD fitted with a PCF8574 I2C backpack
    (the common 1602IIC module) at I2C address 0x27, using the I2C1 master
    PLIB generated by MCC Harmony.

    -------------------------------------------------------------------------
    WHY NON-BLOCKING MATTERS HERE:
    A full LCD screen update (cursor set + 16 characters) requires ~34 I2C
    transactions. At 100 kHz standard-mode I2C each transaction takes ~90 us,
    so a synchronous blocking update costs ~3 ms per ADC sample. During those
    3 ms the main loop cannot call UART_Debug_Process() or UART_BLE_Process(),
    so the 16-byte RX circular queues can fill up and characters are dropped.
    PuTTY shows one sample then appears to time out.

    The fix is a state machine in LCD_Process() that performs exactly ONE I2C
    transaction per main loop iteration. The loop runs at ~MHz, so the full
    screen update completes within ~34 loop iterations (~34 us wall time at
    100 kHz I2C), and the UART queues are drained on every single iteration.
    -------------------------------------------------------------------------

    -------------------------------------------------------------------------
    STATE MACHINE OVERVIEW:
    LCD_Display_ADC() formats the display string into lcdTxBuf[] and sets
    lcdUpdatePending = true.

    LCD_Process() is called every main loop iteration. If an update is pending
    and I2C is free it sends the next byte in lcdTxBuf[] and advances
    lcdTxIndex. When all bytes are sent it clears lcdUpdatePending.

    lcdTxBuf[] is a flat sequence of PCF8574 bytes pre-computed by
    LCD_BuildBuffer(). Building the buffer is fast (no I2C, just bit
    manipulation) and happens synchronously inside LCD_Display_ADC().
    -------------------------------------------------------------------------

    -------------------------------------------------------------------------
    PCF8574 -> HD44780 BIT MAPPING (standard 1602IIC wiring):
      Bit 7 (P7) -> D7
      Bit 6 (P6) -> D6
      Bit 5 (P5) -> D5
      Bit 4 (P4) -> D4
      Bit 3 (P3) -> Backlight (1 = on)
      Bit 2 (P2) -> EN  (latch on falling edge)
      Bit 1 (P1) -> RW  (always 0 = write)
      Bit 0 (P0) -> RS  (0 = command, 1 = data)
    -------------------------------------------------------------------------
*******************************************************************************/

#include <stdio.h>          // sprintf
#include <string.h>         // strlen
#include <stdint.h>
#include <stdbool.h>
#include "lcd.h"
#include "definitions.h"    // I2C1_* PLIB functions from MCC Harmony


// *****************************************************************************
// Section: Configuration
// *****************************************************************************

#define LCD_I2C_ADDR        0x27U   // 7-bit PCF8574 address
#define LCD_COLS            16U
#define LCD_ROWS            2U

/* PCF8574 control bit positions */
#define LCD_BL              (1U << 3)   // Backlight
#define LCD_EN              (1U << 2)   // Enable
#define LCD_RW              (1U << 1)   // Read/Write (always 0 = write)
#define LCD_RS              (1U << 0)   // Register Select (0=cmd, 1=data)

/* HD44780 command bytes */
#define LCD_CMD_CLEAR       0x01U
#define LCD_CMD_ENTRY_MODE  0x06U   // Increment cursor, no display shift
#define LCD_CMD_DISP_OFF    0x08U
#define LCD_CMD_DISP_ON     0x0CU   // Display on, cursor off, blink off
#define LCD_CMD_4BIT_2LINE  0x28U   // 4-bit, 2 lines, 5x8 font
#define LCD_CMD_DDRAM_ROW0  0x80U   // DDRAM address for row 0, col 0
#define LCD_CMD_DDRAM_ROW1  0xC0U   // DDRAM address for row 1, col 0

/*
 * TX buffer sizing.
 *
 * Each HD44780 byte = 2 nibble transfers.
 * Each nibble transfer = 2 PCF8574 bytes (EN high, then EN low).
 * So each HD44780 byte costs 4 entries in lcdTxBuf[].
 *
 * One full screen update:
 *   1 cursor-set command (row 0, if label not written) + 10 chars  = 11 bytes
 *   1 cursor-set command (row 1)                       + 16 chars  = 17 bytes
 *   Total worst case = 28 HD44780 bytes * 4 = 112 PCF8574 bytes.
 *
 * 128 gives comfortable margin.
 */
#define LCD_TX_BUF_SIZE     128U

/*
 * Delay loop counts used ONLY during LCD_Init() (blocking, pre-main-loop).
 * At 72 MHz each loop iteration ~14 ns.
 */
#define LCD_DELAY_POWERON_LOOPS     1100000UL   // ~15 ms
#define LCD_DELAY_INIT_LONG_LOOPS   300000UL    // ~4.2 ms
#define LCD_DELAY_INIT_SHORT_LOOPS  8000UL      // ~110 us
#define LCD_DELAY_CMD_LOOPS         3000UL      // ~42 us
#define LCD_DELAY_CLEAR_LOOPS       120000UL    // ~1.7 ms


// *****************************************************************************
// Section: Private Variables
// *****************************************************************************

/* Backlight state ORed into every PCF8574 byte */
static uint8_t lcdBacklight = LCD_BL;

/*
 * Pre-computed flat sequence of PCF8574 bytes for the next screen update.
 * Built by LCD_BuildBuffer() inside LCD_Display_ADC().
 * Consumed one entry per main loop iteration by LCD_Process().
 */
static uint8_t  lcdTxBuf[LCD_TX_BUF_SIZE];
static uint16_t lcdTxLen   = 0U;    // Number of valid bytes in lcdTxBuf[]
static uint16_t lcdTxIndex = 0U;    // Next byte to send in LCD_Process()

/* Set by LCD_Display_ADC(), cleared by LCD_Process() when all bytes sent */
static volatile bool lcdUpdatePending = false;

/* True after the static "ADC Value:" label has been sent once */
static bool labelWritten = false;


// *****************************************************************************
// Section: Private Functions
// *****************************************************************************

/*
 * LCD_Delay
 * Blocking spin loop. Used ONLY inside LCD_Init() before the main loop.
 */
static void LCD_Delay(volatile uint32_t count)
{
    while (count > 0U) { count--; }
}

/*
 * LCD_I2C_WriteByte_Blocking
 *
 * Sends one byte to the PCF8574 and waits for the transaction to complete.
 * Used ONLY during LCD_Init(). Do not call from LCD_Process().
 */
static void LCD_I2C_WriteByte_Blocking(uint8_t data)
{
    while (I2C1_IsBusy());
    I2C1_Write(LCD_I2C_ADDR, &data, 1U);
    while (I2C1_IsBusy());
}

/*
 * LCD_PulseEnable_Blocking
 *
 * Sends EN-high then EN-low for one nibble. Blocking. Init use only.
 */
static void LCD_PulseEnable_Blocking(uint8_t nibbleByte)
{
    LCD_I2C_WriteByte_Blocking(nibbleByte | LCD_EN);
    LCD_I2C_WriteByte_Blocking(nibbleByte & (uint8_t)(~LCD_EN));
    LCD_Delay(LCD_DELAY_CMD_LOOPS);
}

/*
 * LCD_SendCommand_Blocking
 * Sends an HD44780 command byte (RS=0) as two nibbles. Blocking. Init only.
 */
static void LCD_SendCommand_Blocking(uint8_t cmd)
{
    uint8_t ctrl        = lcdBacklight;              // RS=0, RW=0
    uint8_t upperNibble = (cmd & 0xF0U) | ctrl;
    uint8_t lowerNibble = ((cmd << 4U) & 0xF0U) | ctrl;
    LCD_PulseEnable_Blocking(upperNibble);
    LCD_PulseEnable_Blocking(lowerNibble);
}

/*
 * LCD_AppendByte
 *
 * Appends the 4 PCF8574 bytes that represent one HD44780 byte (two nibble
 * transfers, each as EN-high + EN-low) into lcdTxBuf[] starting at *idx.
 * *idx is advanced by 4 on return.
 *
 * Parameters:
 *   byte - HD44780 command or character byte
 *   rs   - 0 for command, LCD_RS for character data
 *   idx  - Pointer to the current write position in lcdTxBuf[]
 */
static void LCD_AppendByte(uint8_t byte, uint8_t rs, uint16_t *idx)
{
    if ((*idx + 4U) > LCD_TX_BUF_SIZE) { return; }  // Guard: buffer full

    uint8_t ctrl        = rs | lcdBacklight;
    uint8_t upperNibble = (byte & 0xF0U) | ctrl;
    uint8_t lowerNibble = ((byte << 4U) & 0xF0U) | ctrl;

    lcdTxBuf[(*idx)++] = upperNibble | LCD_EN;           // EN high, upper
    lcdTxBuf[(*idx)++] = upperNibble & (uint8_t)(~LCD_EN); // EN low,  upper
    lcdTxBuf[(*idx)++] = lowerNibble | LCD_EN;           // EN high, lower
    lcdTxBuf[(*idx)++] = lowerNibble & (uint8_t)(~LCD_EN); // EN low,  lower
}

/*
 * LCD_AppendCommand
 * Convenience wrapper: appends one HD44780 command byte (RS=0).
 */
static void LCD_AppendCommand(uint8_t cmd, uint16_t *idx)
{
    LCD_AppendByte(cmd, 0U, idx);
}

/*
 * LCD_AppendData
 * Convenience wrapper: appends one HD44780 character data byte (RS=1).
 */
static void LCD_AppendData(uint8_t data, uint16_t *idx)
{
    LCD_AppendByte(data, LCD_RS, idx);
}

/*
 * LCD_BuildBuffer
 *
 * Builds the complete flat PCF8574 byte sequence for a screen update into
 * lcdTxBuf[] and sets lcdTxLen. Called synchronously from LCD_Display_ADC()
 * (no I2C, just bit manipulation, so no blocking concern).
 *
 * Layout:
 *   Row 0: "ADC Value:      " (written once; skipped after labelWritten=true)
 *   Row 1: numeric value left-aligned, padded with spaces to fill 16 columns
 */
static void LCD_BuildBuffer(uint32_t value)
{
    uint16_t idx = 0U;

    // ------------------------------------------------------------------
    // Row 0: static label - only on first call
    // ------------------------------------------------------------------
    if (!labelWritten)
    {
        // Set cursor to row 0, col 0
        LCD_AppendCommand(LCD_CMD_DDRAM_ROW0, &idx);

        const char *label = "ADC Value:      ";   // exactly 16 chars
        for (uint8_t i = 0U; label[i] != '\0'; i++)
        {
            LCD_AppendData((uint8_t)label[i], &idx);
        }
        labelWritten = true;
    }

    // ------------------------------------------------------------------
    // Row 1: numeric ADC value, padded to 16 chars to erase old digits
    // ------------------------------------------------------------------
    char numStr[LCD_COLS + 1U];
    sprintf(numStr, "%-16lu", (unsigned long)value);
    numStr[LCD_COLS] = '\0';  // guarantee null termination

    // Set cursor to row 1, col 0
    LCD_AppendCommand(LCD_CMD_DDRAM_ROW1, &idx);

    for (uint8_t i = 0U; numStr[i] != '\0'; i++)
    {
        LCD_AppendData((uint8_t)numStr[i], &idx);
    }

    lcdTxLen = idx;
}


// *****************************************************************************
// Section: Public Functions
// *****************************************************************************

void LCD_Init(void)
{
    lcdBacklight  = LCD_BL;
    labelWritten  = false;
    lcdUpdatePending = false;
    lcdTxLen      = 0U;
    lcdTxIndex    = 0U;

    // Power-on delay (>15 ms)
    LCD_Delay(LCD_DELAY_POWERON_LOOPS);

    // 4-bit initialisation sequence (HD44780 datasheet Figure 24).
    // Must send upper nibble 0x3 three times in 8-bit mode before switching.
    LCD_PulseEnable_Blocking(0x30U | lcdBacklight);
    LCD_Delay(LCD_DELAY_INIT_LONG_LOOPS);   // >4.1 ms

    LCD_PulseEnable_Blocking(0x30U | lcdBacklight);
    LCD_Delay(LCD_DELAY_INIT_SHORT_LOOPS);  // >100 us

    LCD_PulseEnable_Blocking(0x30U | lcdBacklight);
    LCD_Delay(LCD_DELAY_INIT_SHORT_LOOPS);  // >100 us

    // Switch to 4-bit mode (send upper nibble 0x2 only)
    LCD_PulseEnable_Blocking(0x20U | lcdBacklight);
    LCD_Delay(LCD_DELAY_CMD_LOOPS);

    // Now in 4-bit mode - use LCD_SendCommand_Blocking() from here
    LCD_SendCommand_Blocking(LCD_CMD_4BIT_2LINE);   // 4-bit, 2 lines, 5x8
    LCD_SendCommand_Blocking(LCD_CMD_DISP_OFF);
    LCD_SendCommand_Blocking(LCD_CMD_CLEAR);
    LCD_Delay(LCD_DELAY_CLEAR_LOOPS);               // Clear needs >1.52 ms
    LCD_SendCommand_Blocking(LCD_CMD_ENTRY_MODE);
    LCD_SendCommand_Blocking(LCD_CMD_DISP_ON);      // Display on, cursor off
}

void LCD_Display_ADC(uint32_t value)
{
    // If the previous update hasn't finished sending yet, discard it and
    // start fresh with the newer value. At ~1200 Hz ADC and ~34 loop
    // iterations per update this should never happen in practice, but
    // guard here for safety.
    lcdUpdatePending = false;

    LCD_BuildBuffer(value);

    lcdTxIndex       = 0U;
    lcdUpdatePending = true;
}

void LCD_Process(void)
{
    // Nothing to send, or I2C is still busy from the last transaction
    if (!lcdUpdatePending)          { return; }
    if (I2C1_IsBusy())              { return; }

    // All bytes have been sent - update is complete
    if (lcdTxIndex >= lcdTxLen)
    {
        lcdUpdatePending = false;
        return;
    }

    // Send exactly one PCF8574 byte this iteration and advance the index.
    // We pass a pointer to the buffer slot directly; I2C1_Write() only
    // needs the data to be valid until the transaction completes, and we
    // guard against starting a new one until I2C1_IsBusy() is false again.
    I2C1_Write(LCD_I2C_ADDR, &lcdTxBuf[lcdTxIndex], 1U);
    lcdTxIndex++;
}

/*******************************************************************************
 End of File
*******************************************************************************/
