# Enable Bluetooth
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="PIC32_Bridge"

# Enable the Nordic UART Service (NUS)
CONFIG_BT_NUS=y

# Enable UART drivers for the PIC32 connection
CONFIG_SERIAL=y
CONFIG_UART_ASYNC_API=y
CONFIG_UART_0_NRF_HW_ASYNC=y
CONFIG_UART_0_NRF_HW_ASYNC_TIMER=2

# Enable GPIO for the Push Button and LED
CONFIG_GPIO=y

# Enable RTT for Snooping and Direct Injection
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_LOG=y