/*******************************************************************************
  Main Source File

  File Name:
    main.c

  Summary:
    System entry point and main loop for PIC32MX274F256B ADC/UART application.

  Description:
    Initialises all peripherals then enters the main loop. The main loop is
    intentionally kept thin ? each module owns its own state and exposes a
    single Process() function that is called here on every iteration.

    -------------------------------------------------------------------------
    PERIPHERAL OVERVIEW:
      UART2  - Debug terminal (PC). Commands: "start", "stop". Echo enabled.
      UART1  - BLE module (115200 baud). Same commands. No echo.
      ADC    - Triggered by Timer 3 at ~1200 Hz. Averages 1200 samples (~1s).
      Timer3 - Started/stopped by ADC_Module_Start() / ADC_Module_Stop().
      LED    - On while sampling is active, off when stopped.
    -------------------------------------------------------------------------

    -------------------------------------------------------------------------
    COMMAND FLOW:
      Any UART receives "start" or "stop"
        -> uart_debug.c / uart_ble.c assembles the string
        -> Command_Dispatch() in command.c executes the action
        -> Response sent back over the same UART the command came from
    -------------------------------------------------------------------------

    -------------------------------------------------------------------------
    TO ADD A NEW COMMUNICATION CHANNEL (e.g. USB CDC):
      1. Create the new module (e.g. usb_cdc.c / usb_cdc.h)
      2. #include its header below
      3. Call its Init() function in the initialisation section
      4. Call its Process() function in the main loop
      5. Wire it into command.c (see instructions in command.h / command.c)
    -------------------------------------------------------------------------

    -------------------------------------------------------------------------
    HANDS-OFF FILES (MCC Harmony generated ? do not edit):
      initialization.c, definitions.h, device.h, toolchain_specifics.h,
      xc32_monitor.c, interrupts.c, interrupts.h, exceptions.c,
      plib_uart1.c/h, plib_uart2.c/h, plib_adc.c/h, plib_tmr3.c/h,
      plib_gpio.c/h, plib_evic.c/h, plib_clk.c/h
    -------------------------------------------------------------------------
*******************************************************************************/

#include <stddef.h>         // NULL
#include <stdbool.h>        // true, false
#include <stdlib.h>         // EXIT_FAILURE
#include "definitions.h"    // All MCC Harmony peripheral drivers (hands-off)
#include "adc.h"            // ADC_CallbackRegister(), ADC_Enable(), ADC_Process()
#include "uart_debug.h"     // UART_Debug_Init(), UART_Debug_Process()
#include "uart_ble.h"       // UART_BLE_Init(), UART_BLE_Process()
#include "command.h"        // CMD_Source_t (included for completeness/clarity)


// *****************************************************************************
// Section: Main Entry Point
// *****************************************************************************

int main(void)
{
    // -----------------------------------------------------------------------
    // System Initialisation
    // Initialises all MCC Harmony peripherals in the correct order:
    // Clock -> GPIO -> UART2 -> UART1 -> Timer3 -> ADC -> EVIC -> Interrupts
    // This call is generated by MCC and must remain first.
    // -----------------------------------------------------------------------
    SYS_Initialize(NULL);

    // -----------------------------------------------------------------------
    // LED Setup
    // Configure the LED GPIO pin as an output and turn it on at startup.
    // The LED reflects sampling state: on = sampling active, off = stopped.
    // LED_OutputEnable() and LED_Set() are GPIO macros generated by MCC
    // from the pin label assigned in the Pin Manager.
    // -----------------------------------------------------------------------
    LED_OutputEnable();
    LED_Set();

    // -----------------------------------------------------------------------
    // ADC Setup
    // Register our ADC interrupt callback then enable the ADC peripheral.
    // Timer 3 is NOT started here ? it is started by ADC_Module_Start()
    // when a "start" command is received, and stopped by ADC_Module_Stop().
    // -----------------------------------------------------------------------
    ADC_CallbackRegister(ADC_Callback, 0);
    ADC_Enable();

    // -----------------------------------------------------------------------
    // UART2 Debug Terminal Setup
    // Registers the UART2 RX callback and arms the first 1-byte read.
    // After this, characters received on UART2 are automatically queued
    // by the interrupt and processed in UART_Debug_Process() below.
    // -----------------------------------------------------------------------
    UART_Debug_Init();

    // -----------------------------------------------------------------------
    // UART1 BLE Module Setup
    // Registers the UART1 RX callback and arms the first 1-byte read.
    // After this, characters received on UART1 are automatically queued
    // by the interrupt and processed in UART_BLE_Process() below.
    // -----------------------------------------------------------------------
    UART_BLE_Init();

    // -----------------------------------------------------------------------
    // Main Loop
    // Each Process() call is non-blocking ? if there is nothing to do the
    // function returns immediately. The order here does not matter for
    // correctness but keep ADC_Process() last so UART responses go out
    // before the ADC average is transmitted (avoids interleaved output).
    // -----------------------------------------------------------------------
    while (true)
    {
        // Required by Harmony even when only PLIBs are used.
        // Defined as a no-op macro in definitions.h for this project.
        SYS_Tasks();

        // Drain the UART2 RX queue and dispatch any complete commands.
        // Characters are echoed back to the terminal in here.
        UART_Debug_Process();

        // Drain the UART1 RX queue and dispatch any complete commands.
        // No echo ? BLE central devices do not expect it.
        UART_BLE_Process();

        // When 1200 ADC samples have been accumulated (~1 second at 1200 Hz),
        // calculate the average and transmit it over UART2.
        // This function does nothing if the sample count has not been reached.
        ADC_Process();
    }

    // Unreachable ? required by the C standard for main() returning int.
    return (EXIT_FAILURE);
}

/*******************************************************************************
 End of File
*******************************************************************************/